#!/usr/bin/perl -w

use Test::More 'no_plan';
use Test::Differences;

use_ok 'XS::Writer';

my $writer = XS::Writer->new(
    package   => 'Some::Employee',
    include   => <<'END',
#include "ppport.h"
END

);
isa_ok $writer, 'XS::Writer';
is $writer->package,    "Some::Employee";
is $writer->xs_type,    "Some__Employee";
is $writer->xs_prefix,  "Some__Employee_";
is $writer->xs_file,    "lib/Some/Employee_struct.xs";

$writer->struct(<<'END');
    typedef struct employee {
        char *      name;
        int         salary;
        double      id;
    };
END

eq_or_diff $writer->make_xs, <<"END";
/* Generated by XS::Writer $XS::Writer::VERSION */
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"


typedef employee *     Some__Employee;

MODULE = Some::Employee  PACKAGE = Some::Employee  PREFIX = Some__Employee_

Some::Employee
Some__Employee_new(char* CLASS)
    CODE:
       RETVAL = ((malloc(sizeof(employee))));
        if( RETVAL == NULL ) {
           warn( "unable to create new Some::Employee" );
       }
    OUTPUT:
       RETVAL
END
